# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

end
 desc "Deploy a new alpha version to the Google Play Store"
  lane :fl do
  gradle(task: 'assemble', build_type: 'Release')
    APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    sh("mv #{APK_LOCATION} /Users/Shared/Jenkins/Home/workspace/FastLaneTest/")

    gradle(task: 'assemble', build_type: 'debug')
    APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    sh("mv #{APK_LOCATION} /Users/Shared/Jenkins/Home/workspace/FastLaneTest/")
  end

   desc "Testing "
    lane :pt do
      puts "Hi there"
    end
